language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: L6OrXFDZcZN1UJWGDGYQRngaLYfGSgrMiijXjdVnM3arTUZ3KT64L6nwb3CHxRAjMIAWYDzsAMPNW+67bC70forcIzL/XyWJ2jqarbgq1RBVKtyJ999yhaouKVoNWEW0Lu2CAoe/wJqS6H8lvRq+BwJxIBQkaUWqL4lJtGfS4aUn8zzmJF+w6rkuqhxfjC6PdLVwMPqYX66L3SoFD8Ki0qHoyaAidL0n0MzoIgSSDe/tJon3giZpIo2+Z5DApW1/opdU+V7Mx9s2NRjRwVWMpDGmKXbH4DEakdA+ZrT7Svglbc3RLDlbiw4yEKk4iDTj3xSLc9Obup0JJX5RW1gcTNb8AN8Dg2pQtwbfeLudu5WroHb7TAVXnORLKsnwLhQw2wXE5pJXCW9SJgC4BIHRKYEbhRnUxU/huB/Qu3ehVFySu/5+vpSGr63NmtYB/xB5Rfe4LNqPmw0UwQH4LYQP4L1SeQNjmSZp2CUyfDsu9lpgtEymmR7Cp9KyWfHLDbECSragvIIdN3yBVlR/gbazIFN9WIAuMUx7WiYWBhUMcUogRd/EM1Iy/3JIM4OKNiNM/ifVhEvLTWK0tLMz5vSgMWA6d3QCjegwGCLenEQh/7TuJLfJ2c5ISOIgB3enrjUUXlpXABxbOR+IdaCaJDCPhmPxcsG8I7i+1alg2hczUBc=
  app: itstrending
before_install:
- cd view && yarn