language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: Lf/p22aRAgSC245/VeDZDV00T49PUYrdCyijBwS5LLNvSsWTxQ7clkeWaZHqwpvKkOO55weE3Rasrfg2jmt/ohQcQ+bJ979X2KdHyTp9vd5+UiAOCA+PuCvm4QFt+Atqde/BO0i1dElMkqUfHJGR3Y0AxaaOgMC73nzhRKcGWpLP/wwzDUw9mWDr97BCZuRQB0EsGrRcuZqY48fxm9Kupp5+QWZYkboKoDHWMoEZtjlc2tj7Fl6nhkMqcXXEr7gA4SdVsm3s0G5bSiGi8CwWHiZyRMRbl4Uak/9NRbzK4IDXOMN8bGddQpdmZAh1IiqHw48OubvF2E6iLuh9lg9jw13B+T4IBs5hQnoft6ma96hc2OCtCjtuXiPK14mB1imm4UekAxNUxmlRPuSsC7dsCFzk/9XajWYHOQLJBo+XKfv38P/aLBE+Q3krdC/SauF1JNQdtd66pA55Rp5/FRx13HxzvCCqxwYSiLBOUXnqa7GCiFZ4+MB+nAlOFySIjwcFex8t+fJH04VsaGBu6i+yN2leADVFxs+gFAb/m+cf8DWcNbUFlrw/pwg1531yCnsdoChwk1ob6CiB52IM5IDWAH7HKTHXoome+t+xiFlOHyQsXagBZkBjK5ZhDriZ2VHf6qsULKpEoGhdYH2I047+OXZwcmkZEUvlzu8Ec+Lukgs=
  app: itstrending
  on:
    repo: thektan/trending
before_install:
- cd view && yarn && cd -
